config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  get    "/register",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :articles
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  validates :title,  presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 2000 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  # この記憶ダイジェストを再利用しているのは単に利便性のため
  def session_token
    remember_digest || remember
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params) if logged_in?
    if @article.save
      flash[:success] = "article created!"
      redirect_to articles_path
    else
      flash.now[:danger] = "article did Not created"
      logger.debug @article.errors.full_messages
      render "articles/new" , status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "article edited!"
      redirect_to articles_path
    else
      flash.now[:danger] = "article did Not edited"
      render "articles/edit", status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "article deleted!"
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :tag, :author, :content) # author削除予定
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "User created sucessful, Welcome to Conduit!"
      redirect_to user_url(@user)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end

  # beforeフィルタ

  # ログイン済みユーザーかどうか確認(そのユーザー本人かは関係ない)
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url, status: :see_other
    end
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, status: :see_other) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
    # セッションリプレイ攻撃から保護する
    session[:session_token] = user.session_token
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && session[:session_token] == user.session_token
        @current_user = user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil   # 安全のため
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
    <fieldset>
    <fieldset class="form-group">
        <%= f.text_field :title, class: 'form-control form-control-lg' , placeholder: "Article Title"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_area  :content, class: 'form-control' , placeholder: "Write your article (in markdown)", rows:"8"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field :tag, class: 'form-control' , placeholder: "Enter tags"%>
    </fieldset>
    <%= f.submit "Publish Article", class: "btn btn-lg pull-xs-right btn-primary" %>
    </fieldset>
<% end %>

app/views/articles/edit.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">

        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>

        <%= render "shared/error_messages" , obj: @article %>
        <%= render "form", article: @article %>

      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>

      <% @articles.each do |article| %>
        <div class="article-preview">
          <div class="article-meta">

            <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
            <div class="info">
              <%= link_to "#{article.user.name}" , user_path(article.user.id), class: "author" %>
              <span class="date"><%= article.created_at.strftime('%Y/%m/%d') %></span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> <%= rand(0..100) %>
            </button>
          </div>

          <%= link_to article_path(article.id) , class: "preview-link" do %>
            <h1><%= article.title%></h1>
            <p><%= article.content %></p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline"><%= article.tag %></li>
            </ul>
          <% end %>
        </div>
      <% end %>

    <%= will_paginate @articles , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="editor-page">
  <div class="container page">


    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>

        <%= render "shared/error_messages" , obj: @article %>
        <%= render "form", article: @article %>

      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>

      <div class="article-meta">
        <a href="<%= user_path(@article.user.id) %>"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
        <div class="info">
          <%= link_to "#{@article.user.name}" , user_path(@article.user.id), class: "author" %>
          <span class="date"><%= @article.created_at.strftime('%Y/%m/%d') %></span>
        </div>

      <% if @article.user == current_user %>
        <%= link_to edit_article_path, class: 'edit btn btn-sm btn-outline-secondary' do %>
          <i class="ion-edit"></i>
          &nbsp; Edit Article
        <% end %>

        &nbsp;&nbsp;
        <%= link_to article_path, data: { turbo_method: :delete , turbo_confirm: '本当に削除していいですか?' } , class: 'delete btn btn-sm btn-outline-danger' do %>
          <i class="ion-trash-a"></i>
          &nbsp; Delete Article
        <% end %>
      <% else %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p>
          <%= @article.content %>
        </p>

        <ul class="tag-list">
          <li class="tag-default tag-pill tag-outline"><%= @article.tag %></li>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/conduit/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <title>Conduit</title>
  <!-- Import Ionicon icons & Google Fonts our Bootstrap theme relies on -->
  <link
    href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    rel="stylesheet"
    type="text/css"
  />
  <link
    href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
    rel="stylesheet"
    type="text/css"
  />
  <!-- Import the custom Bootstrap 4 theme from our hosted CDN -->
  <link rel="stylesheet" href="//demo.productionready.io/main.css" />
</head>
<body>

<%= render "layouts/header"%>

<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>

        <div class="article-preview">
          <div class="article-meta">
            <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
            <div class="info">
              <a href="/profile/eric-simons" class="author">Eric Simons</a>
              <span class="date">January 20th</span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> 29
            </button>
          </div>
          <a href="/article/how-to-build-webapps-that-scale" class="preview-link">
            <h1>How to build webapps that scale</h1>
            <p>This is the description for the post.</p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline">realworld</li>
              <li class="tag-default tag-pill tag-outline">implementations</li>
            </ul>
          </a>
        </div>

        <div class="article-preview">
          <div class="article-meta">
            <a href="/profile/albert-pai"><img src="http://i.imgur.com/N4VcUeJ.jpg" /></a>
            <div class="info">
              <a href="/profile/albert-pai" class="author">Albert Pai</a>
              <span class="date">January 20th</span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> 32
            </button>
          </div>
          <a href="/article/the-song-you" class="preview-link">
            <h1>The song you won't ever stop singing. No matter how hard you try.</h1>
            <p>This is the description for the post.</p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline">realworld</li>
              <li class="tag-default tag-pill tag-outline">implementations</li>
            </ul>
          </a>
        </div>

        <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "layouts/footer"%>

</body>
</html>

app/views/conduit/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <%= render "layouts/header"%>

    <div class="article-page">
  <div class="banner">
    <div class="container">
      <h1>How to build webapps that scale</h1>

      <div class="article-meta">
        <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
        <div class="info">
          <a href="/profile/eric-simons" class="author">Eric Simons</a>
          <span class="date">January 20th</span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons <span class="counter">(10)</span>
        </button>
        &nbsp;&nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Post <span class="counter">(29)</span>
        </button>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-edit"></i> Edit Article
        </button>
        <button class="btn btn-sm btn-outline-danger">
          <i class="ion-trash-a"></i> Delete Article
        </button>
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p>
          Web development technologies have evolved at an incredible clip over the past few years.
        </p>
        <h2 id="introducing-ionic">Introducing RealWorld.</h2>
        <p>It's a great solution for learning how other frameworks work.</p>
        <ul class="tag-list">
          <li class="tag-default tag-pill tag-outline">realworld</li>
          <li class="tag-default tag-pill tag-outline">implementations</li>
        </ul>
      </div>
    </div>

    <hr />

    <div class="article-actions">
      <div class="article-meta">
        <a href="profile.html"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
        <div class="info">
          <a href="" class="author">Eric Simons</a>
          <span class="date">January 20th</span>
        </div>

        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons
        </button>
        &nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Article <span class="counter">(29)</span>
        </button>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-edit"></i> Edit Article
        </button>
        <button class="btn btn-sm btn-outline-danger">
          <i class="ion-trash-a"></i> Delete Article
        </button>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <form class="card comment-form">
          <div class="card-block">
            <textarea class="form-control" placeholder="Write a comment..." rows="3"></textarea>
          </div>
          <div class="card-footer">
            <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            <button class="btn btn-sm btn-primary">Post Comment</button>
          </div>
        </form>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
            <span class="mod-options">
              <i class="ion-trash-a"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <%= render "layouts/footer"%>

</body>
</html>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <a href="/" class="logo-font">conduit</a>
    <span class="attribution">
      An interactive learning project from <a href="https://thinkster.io">Thinkster</a>. Code &amp;
      design licensed under MIT.
    </span>
    <%
=begin%>
 <%= debug(params) if Rails.env.development? %> 
<%
=end%>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">conduit</a>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <a class="nav-link active" href="/">Home</a>
      </li>

      <% if logged_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/articles/new">Create Article</a>
        </li>

        <li class="nav-item">
          <%= link_to "Your Profile(#{current_user.name})", current_user , class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Settings", edit_user_path(current_user) , class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, data: { "turbo-method": :delete , turbo_confirm: 'ログアウトしますか?' } , class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login">Sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Sign up</a>
        </li>
      <% end %>


    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Conduit</title>
    <!-- Import Ionicon icons & Google Fonts our Bootstrap theme relies on -->
    <link
      href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Import the custom Bootstrap 4 theme from our hosted CDN -->
    <link rel="stylesheet" href="//demo.productionready.io/main.css" />


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>

    <%= yield %>

    <%= render "layouts/footer"%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul class="error-messages">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="settings-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Your Settings</h1>

        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>

        <ul class="error-messages">
            <%= render "shared/error_messages" , obj: @user %>
        </ul>


  <%= form_with(model: @user, local: true) do |f| %>
    <fieldset>
    <fieldset class="form-group">
        <%= f.text_field :name, class: 'form-control form-control-lg' , placeholder: "Your Name"%>
    </fieldset>

    <%
=begin%>
 <fieldset class="form-group">
    <%= f.text_area  :bio, class: 'form-control form-control-lg' , placeholder: "Short bio about you", rows:"8"%>
    </fieldset> 
<%
=end%>
    <fieldset class="form-group">
    <%= f.text_field :email, class: 'form-control form-control-lg' , placeholder: "Email"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field :password, class: 'form-control form-control-lg' , placeholder: "password"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field :password_confirm, class: 'form-control form-control-lg' , placeholder: "password_confirm"%>
    </fieldset>
    <%= f.submit "Update Settings", class: "btn btn-lg pull-xs-right btn-primary" %>
    </fieldset>
  <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="auth-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Sign up</h1>
        <p class="text-xs-center">
          <a href="/login">Have an account?</a>
        </p>

        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>

        <ul class="error-messages">
            <%= render "shared/error_messages" , obj: @user %>
        </ul>


    <%= form_with(model: @user, local: true) do |f| %>
    <fieldset>
    <fieldset class="form-group">
        <%= f.text_field :name, class: 'form-control form-control-lg' , placeholder: "Username"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field  :email, class: 'form-control form-control-lg' , placeholder: "Email"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field :password, class: 'form-control form-control-lg' , placeholder: "Password"%>
    </fieldset>
    <fieldset class="form-group">
    <%= f.text_field :password_confirmation, class: 'form-control form-control-lg' , placeholder: "Password_Confirm"%>
    </fieldset>
    <%= f.submit "Sign up", class: "btn btn-lg pull-xs-right btn-primary" %>
    </fieldset>
    <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-page">
  <div class="user-info">
    <div class="container">
      <div class="row">
        <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>
        <div class="col-xs-12 col-md-10 offset-md-1">
          <img src="http://i.imgur.com/Qr71crq.jpg" class="user-img" />
          <h4> <%= @user.name %> </h4>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1">
        <div class="articles-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link active" href="">Articles</a>
            </li>
          </ul>
        </div>

      <% @articles.each do |article| %>
        <div class="article-preview">
          <div class="article-meta">

            <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
            <div class="info">
              <%= link_to "#{article.user.name}" , user_path(article.user.id), class: "author" %>
              <span class="date"><%= article.created_at.strftime('%Y/%m/%d') %></span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> <%= rand(0..100) %>
            </button>
          </div>

          <%= link_to article_path(article.id) , class: "preview-link" do %>
            <h1><%= article.title %></h1>
            <p><%= article.content %></p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline"><%= article.tag %></li>
            </ul>
          <% end %>
        </div>
      <% end %>

        <%= will_paginate @articles , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    </div>
  </div>
</div>